### ISSUE TITLE
Unknown field "publishDelay"

### ISSUE THREAD

**Issue by Colin1224** [leotaku/kojirou#2]
Windows:

Running this command
`go run .\kojirou.go d86cf65b-5f6c-437d-a0af-19a31f94ec55 -l en`

Produces error
```
PS C:\Tools\kojirou-master> go run .\kojirou.go bfe0ab22-61fd-4ba1-8667-40c516c2dddd -l en
Error: download chapters: get groups: get groups: decode: json: unknown field "publishDelay"
exit status 1
```

Env:
Windows 10 21H1 19043.1348
go version go1.17.3 windows/amd64

---
Ubuntu:

```
colin1224@DESKTOP-T6HU8OP:~/repos/kojirou$ go run kojirou.go d86cf65b-5f6c-437d-a0af-19a31f94ec55 -l en
Error: download chapters: get groups: get groups: decode: json: unknown field "publishDelay"
exit status 1
```

Env2:
Ubuntu 20.04.3 LTS (WSL2)
go version go1.17.3 linux/amd64

---

Is this a known issue or am I misunderstanding something? It happens with go 1.16.10 as well

**Comment by leotaku** [comment]
Sorry, this is not your fault. MangaDex has updated its API since I last worked on this application. I've just pushed a fix that should solve your problem.

**Comment by Colin1224** [comment]
That worked. Thanks for the quick fix, love the application.
