### ISSUE TITLE
Use own .cbz instead of downloading from MangaDex

### ISSUE THREAD

**Issue by gaslec** [leotaku/kojirou#25]
Hello!
Is there a way to use a cbz (or a zip full of images, even a directory full of images) instead of downloading from MangaDex ? 
You're project is the most convenient way to create azw3 on an ARM computer that I found (kindlegen isn't built for arm), and that would be really nice to not only depend on scanlation and being able to convert purchased cbz.
Thanks in advance, have a good day.

**Comment by leotaku** [comment]
Currently, the project has support for loading chapters and images from the filesystem using the `--disk <directory>` flag. Chapters added this way are always preferred to chapters that could be downloaded from MangaDex, but you still have to provide a MangaDex ID which is used for metadata such as title and author information, as well as chapters that were not provided locally.

Refer to [this comment](https://github.com/leotaku/kojirou/issues/17#issuecomment-1208475519) for the structure the local directory passed to `--disk` should have.

**Comment by gaslec** [comment]
Thanks a lot for your answer, I should have checked a bit more before asking!

**Comment by axu2** [comment]
@gaslec kindlegen can be run from Rosetta. The 64 bit version is available in kindle previewer.
