### ISSUE TITLE
Left to right mode isn't working

### ISSUE THREAD

**Issue by Colin1224** [leotaku/kojirou#26]
I was trying to download chapters and I used the ```-p``` argument to make reading direction left to right, but the reading mode was still right to left on my kindle (had to tap left side of screen to go to next page). This doesn't seem to be a Kindle issue because chapters I downloaded before from the same manga still are left to right, just newly downloaded ones are the issue. I also tried taking out the ```-p``` argument, and the result was the same with and without it, when they should be opposites. Also, I tried an unrelated manga and the issue reoccurred.

Here's the exact command I was using:
```kojirou d7037b2a-874a-4360-8a7b-07f2899152fd -l en -a -k -p -C 1 -o F:\```

**Comment by leotaku** [comment]
Oh, that's right. I must have messed up that functionality at some point. I've created a PR for fixing the issue at #27. Please try it and if everything works for you I'll merge the fix.

**Comment by Colin1224** [comment]
Works as expected now with the commit in the pr. Thanks!
