### ISSUE TITLE
Possible rate limit issue/s

### ISSUE THREAD

**Issue by killergoalie** [leotaku/kojirou#28]
Not really sure if this is a rate limit issue.

I've tried looking at the code but I don't see a debug/verbose option.

When running the following:
`.\kojirou.exe -l en 58be6aa6-06cb-4ca5-bd20-f1392ce451fb --kindle-folder-mode  --autocrop`

It'll get thru a handful 1-3 volumes and then hang, now it just hangs on volume 5 never moving on.
A few times I got the following errors:
`Error: covers: mangadex: chapter 0: image 0: stream error: stream ID 17; CANCEL; received from peer`
`Error: volume 4: pages: mangadex: chapter 23: image 13: stream error: stream ID 259; CANCEL; received from peer`

So far it seems stuck on pulling past Volume 5, let me know if you need me to test anything.

**Comment by leotaku** [comment]
Thanks for reporting! This isn't a ratelimit issue though, just a problem caused by me incorrectly implementing some of the cancelling logic. It seems like one of the images in volume 5 is broken, but instead of returning an error, the current code just blocks indefinitely.

I'll try implementing a fix as soon as I can.

**Comment by leotaku** [comment]
The issue should now be fixed. 

Note that you still won't be able to download volume 5 correctly, as the upload contains broken images. This is a known issue that I can't really do much about, also see #6 and #24 for the reasoning behind this. 

However, now you should be able to get a proper error message, which you can then use to filter out the offending chapters, or load them from a local directory.

**Comment by leotaku** [comment]
@killergoalie Can you confirm the program no longer hangs for you on the latest release?

**Comment by killergoalie** [comment]
Just got back from a business trip, give me a few hours and get the latest release pulled.  Thanks

**Comment by killergoalie** [comment]
Looks good atleast from understand what's failing now.  Thanks for the quick release.  I'm looking over your code as I'm trying to learn GO at the moment. Thanks again, Also side note, Volumes 5, 6, and 7 have that issue =/

**Comment by leotaku** [comment]
Thanks for the response. 

As far as learning Go using this codebase, I think it should be fine, but I would probably try to not replicate the current module structure in your own projects, as it is a bit of a mess right now. Also, note that this is a pre-generics codebase and today you would be able to express a lot of stuff more cleanly by using generics.
