### ISSUE TITLE
"An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by x3vyx** [leotaku/kojirou#30]
Im trying to download some manga, but the longer ones I always get this error and the process stop, anyway to fix it?
I used the mangadex-dl and I get some connection errors too but it just try to download again e continues

**Comment by leotaku** [comment]
Could you send me the manga ID for the manga where you get this error? Normally that error just indicates that your internet connection is too slow and MangaDex is timing you out. 

The code for handling timeouts currently does not retry on failure, but I should be able to fix that relatively quickly.

**Comment by x3vyx** [comment]
ID: af38f328-8df1-4b4c-a272-e737625c3ddc

i think is just because is downloading too many things at the same time an d mangadex just time out me to prevent something

**Comment by leotaku** [comment]
My code should respect all the MangaDex limits, so as long as you are not running multiple instances of `kojirou` in parallel, this should not be an issue. I've also tried to download the manga and I don't get that error, so its probably related to your internet connection.

In any case, I'm interested in fixing my application to work well with less reliable internet connections, and I already have a fix locally. I'll ping you again when I've pushed the fix, although you will have to build the application yourself, or wait for a release to test it.

**Comment by leotaku** [comment]
@x3vyx I've pushed a fix that should address the problem. You can build the application from the master branch and tell me if your problem has been resoved.

**Comment by leotaku** [comment]
I've now also published a new release that incorporates these changes. If you can, please tell me if your problem has been fixed, so I can close this issue. You can also close this issue yourself. Thanks!

**Comment by leotaku** [comment]
The original reporter has not indicated that they still experience the problem reported here. As such, the issue will now be closed
