### ISSUE TITLE
Downloads fail if Manga name contains illegal characters

### ISSUE THREAD

**Issue by dkuester** [leotaku/kojirou#4]
If the Manga contains an illegal character, like in Deadpool: Samurai (https://mangadex.org/title/ef6319e9-9986-4990-a69b-2791d9af8846/), the download fails. At least on Windows, filenames and directories cannot contain colons.

Here's the full error message:
Error: write: mkdir kindle/documents/Deadpool: Samurai: The directory name is invalid.

**Comment by leotaku** [comment]
That is annoying... I'll probably solve this by implementing some custom filename normalisation.

For the time being, you should be able to sidestep this issue by disabling kindle-folder-mode and manually setting the output directory. E.g.:
```
kojirou f6319e9-9986-4990-a69b-2791d9af8846 -o 'Deadpool - Samurai'
```

**Comment by leotaku** [comment]
Illegal characters will now be replaced based on the value of `runtime.GOOS` and a hardcoded list of transformations.
Most characters are replaced by their corresponding Unicode full width equivalents.
