### ISSUE TITLE
Any other site support or any way to optimize downloaded comic?

### ISSUE THREAD

**Issue by UtkarshRa242** [leotaku/kojirou#40]
Hi dev! the tool works perfectly for the website mangadex. However, I was wondering if support for any other website can be added let's say readcomiconline.li.

If not, then suppose I have downloaded a comic from the website. I use calibre for converting it from cbr/cbz to azw3. But it doesn't fit the page like kojirou does. Is there any way to achieve your level of optimization?

**Comment by leotaku** [comment]
I am not planning to add support for any other websites at this time. If you want to convert your downloaded comics to azw3, consider using the `--disk` argument documented in the README, or the [mapaki](https://github.com/tsopeh/mapaki) project which also uses my [mobi](https://github.com/leotaku/mobi) library to generate e-books and thus will produce almost identical output.

**Comment by UtkarshRa242** [comment]
> I am not planning to add support for any other websites at this time. If you want to convert your downloaded comics to azw3, consider using the `--disk` argument documented in the README, or the [mapaki](https://github.com/tsopeh/mapaki) project which also uses my [mobi](https://github.com/leotaku/mobi) library to generate e-books and thus will produce almost identical output.

The mapaki project works fabulous for me. Thanks a lot dev. I am speechless. Thanks a lot!!!!!!!!!!!!!!!
