### ISSUE TITLE
Feature request: add option to double pages

### ISSUE THREAD

**Issue by alvarosoaress** [leotaku/kojirou#44]
Hello!

I wanted to ask if it's possible to add a customizable option to handle double panel pages in mangas, like KCC, where double page spreads will be displayed twice. First rotated and then Split.

It's possible to add this type of customization here in kojirou ?

**Comment by leotaku** [comment]
Hi, sorry for keeping you waiting. The tool [mapaki](https://github.com/tsopeh/mapaki) which is based on the same MOBI generation code as this project already has your desired page-split handling as an option. I might implement something similar here in the future, but as for right now, I recommend trying that tool.

**Comment by leotaku** [comment]
Hi again! I've now implemented this, so I will close this issue.
