### ISSUE TITLE
Failure when getting authors in some manga

### ISSUE THREAD

**Issue by Colin1224** [leotaku/kojirou#7]
I've found some manga where there is an error upon trying to pull chapter list.

Example:

```
PS C:\repos\kojirou> go run .\kojirou.go 37f5cce0-8070-4ada-96e5-fa24b1bd4ff9 -l en -d
Error: download: manga: get authors: decode: json: cannot unmarshal object into Go struct field .Data.Attributes.Biography of type []string
exit status 1
```

Also happens for `de4b3c43-5243-4399-9fc3-68a3c0747138`.

**Comment by leotaku** [comment]
So apparently empty LocalizedString objects are arrays? That's... a choice I guess.

**Comment by leotaku** [comment]
Should be fixed now.
