### ISSUE TITLE
Add Installation Instructions

### ISSUE THREAD

**Issue by FiberJW** [leotaku/kojirou#8]
Thanks for building this! This will breathe new life into my Kindle.

I ended up figuring out a way to run it (install Go on Mac and `go run kojirou.go <ARGS>`), but for people less experienced than me and more unfamiliar with Go, it would be nice to provide instructions on how to install this CLI and run it like how you show in the Readme.

Thanks again!

**Comment by leotaku** [comment]
Good idea, thanks!

If you think the instructions are unclear, feel free to reopen this issue. Maybe I could also set up CI to provide prebuilt executables, but I think the instructions are easy enough to follow.

**Comment by TripleWhy** [comment]
I have never used go before, so this might totally be my ignorance, but I could absolutely not make it work with the instructions provided on the main page; even trying different environments and go versions. I finally decided to check the github issues, and the command above instantly made it work. (Assuming you do a git clone before.)

**Comment by leotaku** [comment]
@TripleWhy That's probably my fault, I'd like my tool to be usable for people without any Go experience. Maybe you could tell me what exactly did not work about the installation instructions in the README? Maybe your shell reported a "command not found" after the installation?

**Comment by TripleWhy** [comment]
First it didn't install. I later found out that was at least partially due to me not starting a new shell after installing go. Then it couldn't find the command, yes. I also searched the file system for any files called kojirou, but only found go's download cache.

**Comment by TripleWhy** [comment]
The most accessible way would certainly be to provide a binary

**Comment by leotaku** [comment]
@TripleWhy Agreed! I have already set up a workflow to build executables for different architectures and OSs. ([example](https://github.com/leotaku/kojirou/actions/runs/2147533569)) However, I still need to find a good way to present them to end users, as there doesn't seem to be a way to just link to the latest artefacts.

I'm thinking about using an automatically generated Wiki page, as that's already how I present the CLI documentation.

**Comment by leotaku** [comment]
We now provide prebuilt binaries!
