### ISSUE TITLE
Feature Request: Autocrop

### ISSUE THREAD

**Issue by TripleWhy** [leotaku/kojirou#9]
My kindle papwerwhite doesn't have a very big or high resolution screen. Many mangas have white borders. If there was some way to automatically crop white or black borders, the images could be a bit bigger. I think that would help quite a lot.

**Comment by leotaku** [comment]
This seems like an interesting idea, but potentially hard to implement well. Could you maybe send me a few links for manga titles that have these borders, so I can better understand what you mean?

**Comment by TripleWhy** [comment]
You don't have to look very far, just click a few random links on the landing page:
https://mangadex.org/title/304ceac3-8cdb-4fe7-acf7-2b6ff7a60613
https://mangadex.org/title/aa6c76f7-5f5f-46b6-a800-911145f81b9b
https://mangadex.org/title/70fe972b-3c88-4165-b9a5-3db96d6d2c14
https://mangadex.org/title/a96676e5-8ae2-425e-b549-7f15dd34a6d8 <- This one has borders on all four sides most of the time, sometimes those are a gray pattern.

I'm not expecting any miracles, so just walking through all the pixels from each side and cropping every line that has only the same color as the border should be good enough. You could also just use ImageMagick: http://www.imagemagick.org/script/command-line-options.php#trim

**Comment by flesnuk** [comment]
Just for reference, this is the code used in the Kindle Comic Converter. 
https://github.com/ciromattia/kcc/blob/4ec4c9966c727d6dac44507d34607bd7d2c5ed5c/kindlecomicconverter/image.py#L302-L334
https://github.com/python-pillow/Pillow/blob/95cff6e959bb3c37848158ed2145d49d49806a31/src/libImaging/GetBBox.c#L33

For doing convolution filters in Go (gaussian filter, etc), this library can be useful: https://github.com/disintegration/imaging/blob/master/convolution.go

**Comment by leotaku** [comment]
Autocrop support has been merged quite some time ago so I think this issue can be closed.
